name: cahnhilliard
channels:
  - gpytorch
  - pytorch
  - defaults
dependencies:
  - gpytorch=0.3.6
  - matplotlib=3.1.1
  - numpy=1.16.5
  - pip=20.0.2
  - pyopenssl=19.1.0
  - python=3.6.9
  - cudatoolkit=10.1
  - pytorch=1.4.0=py3.6_cuda101_cudnn7_0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - torchvision=0.5.0=py36_cu101
  - pip:
    - gpy==1.9.9
    - gpyopt==1.2.5
    - opt-einsum==3.1.0
    - paramz==0.9.5
    - pydoe==0.3.8
    - pyro-ppl==0.4.1
    - torchdiffeq==0.0.1
